/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.Date;
import producao.*;

/**
 *
 * @author André
 */
public class Simulador extends javax.swing.JFrame {

    public static boolean Controle = false;
    private Auxiliar aux = new Auxiliar(0, 0, 0, 0);
    private Estoque Estoque_Motores,
            Estoque_Carrocerias,
            Estoque_Pneus,
            Estoque_Bancos,
            Estoque_Eletronicos;
    private LPMotores Linha_Motores;
    private LPCarrocerias Linha_Carrocerias;
    private LPPneus Linha_Pneus;
    private LPBancos Linha_Bancos;
    private LPEletronica Linha_Eletronica;
    private LPMontagem Linha_Montagem;
    /**
     * Creates new form Simulador
     */
    
    public LPMontagem getLinha_Montagem(){
        return Linha_Montagem;
    }
    public Simulador() {
        initComponents();
        Estoque_Motores = new Estoque(10, 12, Barra_Motores, Status_Motores);
        Estoque_Carrocerias = new Estoque(20, 15, Barra_Carrocerias, Status_Carrocerias);
        Estoque_Pneus = new Estoque(100, 9, Barra_Pneus, Status_Pneus);
        Estoque_Bancos = new Estoque(25, 6, Barra_Bancos, Status_Bancos);
        Estoque_Eletronicos = new Estoque(8, 7, Barra_Eletronicos, Status_Eletronicos);
        Barra_Bancos.setMinimum(0);
        Barra_Bancos.setValue(0);
        Barra_Bancos.setMaximum(Estoque_Bancos.getCapacidade());
        Barra_Pneus.setMinimum(0);
        Barra_Pneus.setValue(0);
        Barra_Pneus.setMaximum(Estoque_Pneus.getCapacidade());
        Barra_Motores.setMinimum(0);
        Barra_Motores.setValue(0);
        Barra_Motores.setMaximum(Estoque_Motores.getCapacidade());
        Barra_Carrocerias.setMinimum(0);
        Barra_Carrocerias.setValue(0);
        Barra_Carrocerias.setMaximum(Estoque_Carrocerias.getCapacidade());
        Barra_Eletronicos.setMinimum(0);
        Barra_Eletronicos.setValue(0);
        Barra_Eletronicos.setMaximum(Estoque_Eletronicos.getCapacidade());
        Veiculos.setMinimum(0);
        Veiculos.setValue(0);
        Veiculos.setMaximum(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Guias = new javax.swing.JTabbedPane();
        Linha_de_Producao = new javax.swing.JPanel();
        Barra_Motores = new javax.swing.JProgressBar();
        Label_Motores = new javax.swing.JLabel();
        Barra_Carrocerias = new javax.swing.JProgressBar();
        Label_Carrocerias = new javax.swing.JLabel();
        Informacoes = new javax.swing.JLabel();
        Barra_Pneus = new javax.swing.JProgressBar();
        Label_Pneus = new javax.swing.JLabel();
        Barra_Bancos = new javax.swing.JProgressBar();
        Label_Bancos = new javax.swing.JLabel();
        Barra_Eletronicos = new javax.swing.JProgressBar();
        Label_Eletronico = new javax.swing.JLabel();
        Veiculos = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        Combo_Velocidades = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Botao_Iniciar = new javax.swing.JButton();
        Botao_Sair = new javax.swing.JButton();
        Status_Motores = new javax.swing.JLabel();
        Status_Carrocerias = new javax.swing.JLabel();
        Status_Pneus = new javax.swing.JLabel();
        Status_Bancos = new javax.swing.JLabel();
        Status_Eletronicos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Campo_CarrosHora = new javax.swing.JLabel();
        Campo_TMedio = new javax.swing.JLabel();
        Campo_Total = new javax.swing.JLabel();
        Campo_Prontos = new javax.swing.JLabel();
        Campo_Entregues = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUDI");

        Barra_Motores.setStringPainted(true);

        Label_Motores.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Label_Motores.setText("Estoque de Motores");

        Barra_Carrocerias.setStringPainted(true);

        Label_Carrocerias.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Label_Carrocerias.setText("Estoque de Carrocerias");

        Informacoes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Informacoes.setText("Informações da Produção");

        Barra_Pneus.setStringPainted(true);

        Label_Pneus.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Label_Pneus.setText("Estoque de Pneus");

        Barra_Bancos.setStringPainted(true);

        Label_Bancos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Label_Bancos.setText("Estoque de Bancos");

        Barra_Eletronicos.setStringPainted(true);

        Label_Eletronico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Label_Eletronico.setText("Estoque de Eletrônicos");

        Veiculos.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Veículos no Caminhão");

        Combo_Velocidades.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        Combo_Velocidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Selecione a Velocidade:");

        Botao_Iniciar.setText("Iniciar");
        Botao_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_IniciarActionPerformed(evt);
            }
        });

        Botao_Sair.setText("Sair");
        Botao_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SairActionPerformed(evt);
            }
        });

        Status_Motores.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Status_Motores.setText("Produzindo");

        Status_Carrocerias.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Status_Carrocerias.setText("Produzindo");

        Status_Pneus.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Status_Pneus.setText("Produzindo");

        Status_Bancos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Status_Bancos.setText("Produzindo");

        Status_Eletronicos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Status_Eletronicos.setText("Produzindo");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("André Dias e Rafael Félix");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("Sistemas Distribuídos");

        javax.swing.GroupLayout Linha_de_ProducaoLayout = new javax.swing.GroupLayout(Linha_de_Producao);
        Linha_de_Producao.setLayout(Linha_de_ProducaoLayout);
        Linha_de_ProducaoLayout.setHorizontalGroup(
            Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Linha_de_ProducaoLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(Informacoes)
                .addGap(124, 124, 124))
            .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                        .addComponent(Label_Motores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Linha_de_ProducaoLayout.createSequentialGroup()
                        .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                                .addComponent(Barra_Motores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Status_Motores))
                            .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                                .addComponent(Barra_Pneus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Status_Pneus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Linha_de_ProducaoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combo_Velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Veiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                        .addComponent(Label_Bancos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_Sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Linha_de_ProducaoLayout.createSequentialGroup()
                        .addComponent(Barra_Bancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Status_Bancos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_Iniciar))
                    .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                        .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(Label_Eletronico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                        .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Carrocerias)
                            .addComponent(Label_Pneus)
                            .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                                .addComponent(Barra_Carrocerias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Status_Carrocerias))
                            .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                                .addComponent(Barra_Eletronicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Status_Eletronicos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Linha_de_ProducaoLayout.setVerticalGroup(
            Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Linha_de_ProducaoLayout.createSequentialGroup()
                        .addComponent(Informacoes)
                        .addGap(32, 32, 32)
                        .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Barra_Motores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Status_Motores)))
                    .addComponent(Veiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Motores)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Barra_Carrocerias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status_Carrocerias))
                .addGap(10, 10, 10)
                .addComponent(Label_Carrocerias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Barra_Pneus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Combo_Velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(Status_Pneus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Pneus)
                .addGap(10, 10, 10)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Barra_Bancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Status_Bancos)
                        .addComponent(Botao_Iniciar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Bancos)
                    .addComponent(Botao_Sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Barra_Eletronicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status_Eletronicos))
                .addGap(11, 11, 11)
                .addComponent(Label_Eletronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(Linha_de_ProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20))
        );

        Guias.addTab("Linha de Produção", Linha_de_Producao);

        Campo_CarrosHora.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Campo_CarrosHora.setText("Carros por hora:");

        Campo_TMedio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Campo_TMedio.setText("Tempo médio de produção:");

        Campo_Total.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Campo_Total.setText("Total fabricados:");

        Campo_Prontos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Campo_Prontos.setText("Prontos para entrega:");

        Campo_Entregues.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Campo_Entregues.setText("Carros entregues: ");

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Titulo.setText("Resultados da Execução");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Campo_Entregues)
                            .addComponent(Campo_Total)
                            .addComponent(Campo_CarrosHora)
                            .addComponent(Campo_TMedio)
                            .addComponent(Campo_Prontos))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(Campo_Entregues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_Prontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_Total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_TMedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_CarrosHora)
                .addGap(97, 97, 97))
        );

        Guias.addTab("Mais Resultados", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guias)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guias)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SairActionPerformed
        // TODO add your handling code here:
        switch (Botao_Sair.getText()){
        case "Sair":
            System.exit(0);
            break;
        case "Parar":
            Botao_Iniciar.setText("Iniciar");
            Botao_Sair.setText("Sair");
            Controle = false;
            Estoque_Motores = new Estoque(10, 12, Barra_Motores, Status_Motores);
            Estoque_Carrocerias = new Estoque(20, 15, Barra_Carrocerias, Status_Carrocerias);
            Estoque_Pneus = new Estoque(100, 9, Barra_Pneus, Status_Pneus);
            Estoque_Bancos = new Estoque(25, 6, Barra_Bancos, Status_Bancos);
            Estoque_Eletronicos = new Estoque(8, 7, Barra_Eletronicos, Status_Eletronicos);
            Veiculos.setValue(0);
            break;
        }
    }//GEN-LAST:event_Botao_SairActionPerformed

    public void setvelocidade(){
        this.velocidade = Integer.parseInt
            ((String)this.Combo_Velocidades.getSelectedItem());
        Estoque_Motores.setvelocidade(velocidade);
        Estoque_Carrocerias.setvelocidade(velocidade);
        Estoque_Pneus.setvelocidade(velocidade);
        Estoque_Bancos.setvelocidade(velocidade);
        Estoque_Eletronicos.setvelocidade(velocidade);
    }
    
    private void Botao_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_IniciarActionPerformed
        // TODO add your handling code here:
        switch (Botao_Iniciar.getText()){
        case "Pausar":
            Botao_Iniciar.setText("Continuar");
            Controle = false;
            break;
        default:
            this.setvelocidade();
            Controle = true;
            Botao_Iniciar.setText("Pausar");
            Botao_Sair.setText("Parar");
            proximo = new Date(System.currentTimeMillis());
            ultimo = new Date(proximo.getTime());
            Linha_Motores = new LPMotores(Estoque_Motores, velocidade);
            Linha_Motores.start();
            Linha_Carrocerias = new LPCarrocerias(Estoque_Carrocerias, velocidade);
            Linha_Carrocerias.start();
            Linha_Pneus = new LPPneus(Estoque_Pneus, velocidade);
            Linha_Pneus.start();
            Linha_Bancos = new LPBancos(Estoque_Bancos, velocidade);
            Linha_Bancos.start();
            Linha_Eletronica = new LPEletronica(Estoque_Eletronicos, velocidade);
            Linha_Eletronica.start();
            Linha_Montagem = new LPMontagem(Estoque_Motores, Estoque_Carrocerias, Estoque_Pneus,
                Estoque_Bancos, Estoque_Eletronicos, this.Veiculos, velocidade, aux);
            Linha_Montagem.start();
        }
    }//GEN-LAST:event_Botao_IniciarActionPerformed

    public void updateResultados(){
        
        Campo_CarrosHora.setText("Carros por hora: " + aux.getProducaoHora());
        Campo_Entregues.setText("Carros entregues: " + aux.getEntregues());
        Campo_TMedio.setText("Tempo médio de produção: " + aux.getTempoMedio());
        Campo_Prontos.setText("Carros prontos para entrega: " + Linha_Montagem.getProntos());
        Campo_Total.setText("Total de carros produzidos: " + aux.getProduzidos());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                init = new Simulador();
                init.setVisible(true);
            }
        });
    }
    
    public static int getvelocidade(){
        return 1;
    }

    public static Simulador init;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra_Bancos;
    private javax.swing.JProgressBar Barra_Carrocerias;
    private javax.swing.JProgressBar Barra_Eletronicos;
    private javax.swing.JProgressBar Barra_Motores;
    private javax.swing.JProgressBar Barra_Pneus;
    private javax.swing.JButton Botao_Iniciar;
    private javax.swing.JButton Botao_Sair;
    private javax.swing.JLabel Campo_CarrosHora;
    private javax.swing.JLabel Campo_Entregues;
    private javax.swing.JLabel Campo_Prontos;
    private javax.swing.JLabel Campo_TMedio;
    private javax.swing.JLabel Campo_Total;
    private javax.swing.JComboBox<String> Combo_Velocidades;
    private javax.swing.JTabbedPane Guias;
    private javax.swing.JLabel Informacoes;
    private javax.swing.JLabel Label_Bancos;
    private javax.swing.JLabel Label_Carrocerias;
    private javax.swing.JLabel Label_Eletronico;
    private javax.swing.JLabel Label_Motores;
    private javax.swing.JLabel Label_Pneus;
    private javax.swing.JPanel Linha_de_Producao;
    private javax.swing.JLabel Status_Bancos;
    private javax.swing.JLabel Status_Carrocerias;
    private javax.swing.JLabel Status_Eletronicos;
    private javax.swing.JLabel Status_Motores;
    private javax.swing.JLabel Status_Pneus;
    private javax.swing.JLabel Titulo;
    private javax.swing.JProgressBar Veiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private int velocidade = 1;
    public Date ultimo, proximo;
}
